# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 🖥️ Cloud | 🔄 DevOps | ⚡ Automation | 🛡️ Security 
email: ajomathiu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Everything I have experienced and experimented on cloud and Deployments
twitter_username: ajo_mathew
github_username: ajo.mathew
minimal_mistakes_skin: "air"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ajo Mathew"
  # avatar : "/assets/images/bio-photo.jpg"
  bio    : "I am a highly skilled Cloud and DevOps Architect with over 12 years of experience in designing, deploying, and managing cloud infrastructure across Azure and AWS. My expertise lies in cloud automation, DevOps implementation, infrastructure as code (IaC), and CI/CD pipeline development to optimize application performance and scalability."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://blog.ajomathew.dev"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ajo_mathew"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ajo.mathew"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ajomathiu/"
    - label: "Portfolio"
      icon: "fas fa-fw fa-briefcase"
      url: "http://blog.ajomathew.dev/portfolio"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ajo_mathew"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ajo.mathew"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ajomathiu/"
    - label: "Book time with me"
      icon: "fas fa-fw fa-calendar"
      url: "https://cal.com/ajo-mathew-xiiuah/30min"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
analytics:
  provider               : "custom" 