baseURL = "https://ajomathew.github.io/"
disablePathToLower = true
locale = "en-us"
title = "Ajo's Blog on 🖥️ Cloud 🔄 DevOps ⚡ Automation 🛡️ Security"
theme = "m10c"

[markup.goldmark.renderer]
unsafe = true

[pagination]
  pagerSize = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 4

[params]
  author = "Ajo Mathew"
  description = "Blog about Cloud, DevOps, Automation, and Security"
  menu_item_separator = " - "
  
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/ajomathew"
  [[params.social]]
    icon = "brand-linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/ajomathiu"
